[package]
name = "play-ball"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.0"
rand = "0.8.5"
bevy_asset_loader = "0.18.0"
bevy_audio = "0.12.0"
